# Generated by Django 3.2.3 on 2021-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='电子邮箱')),
                ('username', models.CharField(default='', max_length=16, verbose_name='登录账号')),
                ('password', models.CharField(max_length=128, unique=True, verbose_name='账号密码')),
                ('name', models.CharField(default='', max_length=16, verbose_name='你的名字')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否是超级管理员')),
                ('is_staff', models.BooleanField(default=True, verbose_name='是否是管理员')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'users',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='files')),
                ('type', models.IntegerField(choices=[(0, '未知'), (201, 'ZIP压缩包'), (202, 'RAR压缩包')], default=0, verbose_name='文件类型')),
                ('desc', models.TextField(default='', max_length=255, verbose_name='使用说明')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
                'db_table': 'files',
                'ordering': ['-id'],
                'permissions': (),
            },
        ),
    ]
