# Generated by Django 3.2.3 on 2021-07-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('report_manage', '0002_cardevicepositionmodel'), ('report_manage', '0003_auto_20210623_1132'), ('report_manage', '0004_auto_20210623_1417'), ('report_manage', '0005_alter_errorlevelmodel_error_name'), ('report_manage', '0006_levelerrornumbermodel_test_version_num'), ('report_manage', '0007_remove_levelerrornumbermodel_test_version_num'), ('report_manage', '0008_auto_20210625_1049'), ('report_manage', '0009_alter_levelerrornumbermodel_table'), ('report_manage', '0010_auto_20210625_1102'), ('report_manage', '0011_alter_reporttotalmodel_options'), ('report_manage', '0012_auto_20210629_1630')]

    dependencies = [
        ('report_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDevicePositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('car', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='report_manage.carinfomodel')),
                ('position', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='report_manage.devicepositionmodel')),
            ],
            options={
                'db_table': 'car_device_position',
                'permissions': (),
            },
        ),
        migrations.RenameModel(
            old_name='TestTypeInfo',
            new_name='TestTypeInfoModel',
        ),
        migrations.CreateModel(
            name='ErrorInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_name', models.CharField(default='', max_length=128, verbose_name='错误名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '异常类型管理',
                'verbose_name_plural': '异常类型管理',
                'db_table': 'error_info',
                'ordering': ['-id'],
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ErrorLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, unique=True, verbose_name='异常级别')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'error_level',
                'ordering': ['-level'],
                'permissions': (),
                'verbose_name': '异常级别',
                'verbose_name_plural': '异常级别',
            },
        ),
        migrations.CreateModel(
            name='LevelErrorNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='异常数量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('error_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='report_manage.errorlevelmodel')),
                ('test_version', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='report_manage.testversionmodel')),
            ],
            options={
                'db_table': 'level_error_number',
                'ordering': ['-id'],
                'permissions': (),
            },
        ),
        migrations.AlterModelTable(
            name='levelerrornumbermodel',
            table='error_level_number',
        ),
        migrations.CreateModel(
            name='ErrorNameLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('error_name', models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='report_manage.errorinfomodel')),
                ('level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='report_manage.errorlevelmodel')),
            ],
            options={
                'verbose_name': '异常级别管理',
                'verbose_name_plural': '异常级别管理',
                'db_table': 'error_name_level',
                'ordering': ['level'],
                'permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='reporttotalmodel',
            options={'ordering': ['-create_time'], 'permissions': ()},
        ),
        migrations.RemoveField(
            model_name='reporterrororiginmodel',
            name='activity_pause_timeout',
        ),
        migrations.RemoveField(
            model_name='reporterrortotalmodel',
            name='activity_pause_timeout',
        ),
    ]
